# Generated by Django 4.1.7 on 2023-02-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('technews', 'technews'), ('software', 'software'), ('gaming', 'gaming'), ('esports', 'esports')], max_length=8, null=True),
        ),
    ]
