# Generated by Django 4.1.7 on 2023-02-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_article_name_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='phase',
            field=models.CharField(blank=True, choices=[('technews', 'SBM'), ('software', 'PUB'), ('gaming', 'REJ'), ('esports', 'ARC')], max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(blank=True, choices=[('technews', 'technews'), ('software', 'software'), ('gaming', 'gaming'), ('esports', 'esports')], max_length=8, null=True),
        ),
    ]
