# Generated by Django 4.1.7 on 2023-02-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_article_phase_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='phase',
            field=models.CharField(blank=True, choices=[('DFT', 'DFT'), ('SBM', 'SBM'), ('PUB', 'PUB'), ('REJ', 'REJ'), ('ARC', 'ARC')], max_length=20),
        ),
    ]
