# Generated by Django 4.1.7 on 2023-02-26 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='display_name',
            new_name='user_name',
        ),
    ]
